// config/roles.js (नई फ़ाइल – बैकएंड में कहीं भी रख सकते हैं, e.g., src/config/roles.js)
const NGO_ORGANIZATIONAL_ROLES = [
  'ADDITIONAL_DIRECTOR',
  'STATE_DEVELOPMENT_COORDINATOR',
  'DISTRICT_BRANCH_MANAGER',
  'DISTRICT_PRESIDENT',
  'DISTRICT_FIELD_COORDINATOR',
  'BAMS_DOCTOR',
  'BLOCK_DEVELOPMENT_COORDINATOR',
  'GRAM_DEVELOPMENT_COORDINATOR',
];

module.exports = { NGO_ORGANIZATIONAL_ROLES };